export type Doctor = {
  name: string;
  education: string;
  post: string;
  image: string;
  facebook?: string;
  instagram?: string;
  linkedin?: string;
  slug: string;
  experience: string;
  phone: string;
  email: string;
  website: string;
  branch: string;
  consultationFee: string;
  visitingDays: string;
  visitingTime: string;
  languages: string[];
  medibuddyDiscount: string;
  expertise: string[];
};
